/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#005db8",
        "primary-fixed": "#d6e3ff",
        "on-background": "#1a1b1e",
        "on-error": "#ffffff",
        "outline-variant": "#c4c6d0",
        "surface-bright": "#faf9fd",
        "tertiary-fixed": "#f9d8fd",
        background: "#faf9fd",
        "secondary-fixed": "#dae2f9",
        "on-secondary-fixed": "#131c2b",
        "surface-container-high": "#e9e7ec",
        error: "#ba1a1a",
        "secondary-container": "#dae2f9",
        "on-primary-fixed": "#001b3e",
        tertiary: "#6f5575",
        "surface-dim": "#dad9dd",
        "secondary-fixed-dim": "#bec7dc",
        secondary: "#565f71",
        "on-surface-variant": "#44474e",
        "on-primary": "#ffffff",
        "surface-variant": "#e0e2ec",
        "on-secondary-fixed-variant": "#3e4759",
        "on-tertiary-container": "#28132e",
        "surface-container-lowest": "#ffffff",
        outline: "#74777f",
        "surface-container": "#efedf1",
        "surface-container-highest": "#e3e2e6",
        "tertiary-container": "#f9d8fd",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#dcbce0",
        "on-tertiary-fixed-variant": "#563e5c",
        "inverse-primary": "#aac7ff",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f4f3f7",
        "on-surface": "#1a1b1e",
        "on-error-container": "#410002",
        surface: "#faf9fd",
        "on-tertiary-fixed": "#28132e",
        "on-primary-fixed-variant": "#00468d",
        "primary-fixed-dim": "#aac7ff",
        "primary-container": "#d6e3ff",
        "on-secondary-container": "#131c2b",
        "inverse-on-surface": "#f1f0f4",
        "inverse-surface": "#2f3033",
        primary: "#005db8",
        "on-primary-container": "#001b3e",
        bone: "#F5F5F0",
      },
      boxShadow: {
        card: "0px 1px 2px rgba(16,24,40,0.06), 0px 1px 3px rgba(16,24,40,0.10)",
        "card-hover": "0px 4px 8px rgba(16,24,40,0.12), 0px 2px 4px rgba(16,24,40,0.08)",
        float: "0px 8px 24px rgba(16,24,40,0.12)",
        button: "inset 0px -2px 0px rgba(0,0,0,0.12)",
        "button-active": "inset 0px 2px 4px rgba(0,0,0,0.12)",
        toast: "0px 12px 32px rgba(16,24,40,0.18)",
      },
      spacing: {
        "section-margin": "24px",
        "touch-target-min": "50px",
        gutter: "16px",
        "container-padding": "20px",
        "element-gap": "14px",
      },
      fontFamily: {
        "headline-md": ["Work Sans", "sans-serif"],
        "label-lg": ["Public Sans", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
        "button-text": ["Public Sans", "sans-serif"],
        "headline-lg": ["Work Sans", "sans-serif"],
        "metric-xl": ["Work Sans", "sans-serif"],
        "metric-lg": ["Work Sans", "sans-serif"],
        "display-lg": ["Work Sans", "sans-serif"],
        "body-lg": ["Public Sans", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-lg": ["18px", { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "button-text": ["18px", { lineHeight: "20px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "metric-xl": ["32px", { lineHeight: "32px", fontWeight: "700" }],
        "metric-lg": ["20px", { lineHeight: "24px", fontWeight: "700" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["20px", { lineHeight: "30px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
