/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#1366D9",
        "primary-fixed": "#EAF1FD",
        "on-background": "#1B2430",
        "on-error": "#ffffff",
        "outline-variant": "#DCE0E6",
        "surface-bright": "#F0F1F3",
        "tertiary-fixed": "#f9d8fd",
        background: "#F0F1F3",
        "secondary-fixed": "#E8F1FD",
        "on-secondary-fixed": "#0f56b6",
        "surface-container-high": "#E6E8EC",
        error: "#DA3E33",
        "secondary-container": "#E8F1FD",
        "on-primary-fixed": "#0B3A75",
        tertiary: "#6E5AE0",
        "surface-dim": "#D0D3D9",
        "secondary-fixed-dim": "#CFE0F8",
        secondary: "#48505E",
        "on-surface-variant": "#667085",
        "on-primary": "#ffffff",
        "surface-variant": "#E6E8EC",
        "on-secondary-fixed-variant": "#1F4E96",
        "on-tertiary-container": "#2A1F5E",
        "surface-container-lowest": "#ffffff",
        outline: "#D0D3D9",
        "surface-container": "#E6E8EC",
        "surface-container-highest": "#DCE0E6",
        "tertiary-container": "#f9d8fd",
        "error-container": "#FDECEA",
        "tertiary-fixed-dim": "#dcbce0",
        "on-tertiary-fixed-variant": "#563e5c",
        "inverse-primary": "#7FB2F7",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#F8F9FB",
        "on-surface": "#1B2430",
        "on-error-container": "#7A1D15",
        surface: "#F0F1F3",
        "on-tertiary-fixed": "#28132e",
        "on-primary-fixed-variant": "#00468d",
        "primary-fixed-dim": "#CFE0F8",
        "primary-container": "#EAF1FD",
        "on-secondary-container": "#0f56b6",
        "inverse-on-surface": "#f1f0f4",
        "inverse-surface": "#2F3033",
        primary: "#1366D9",
        "on-primary-container": "#0B3A75",
        bone: "#F5F5F0",
      },
      boxShadow: {
        card: "0px 1px 2px rgba(16,24,40,0.06), 0px 1px 3px rgba(16,24,40,0.10)",
        "card-hover": "0px 4px 8px rgba(16,24,40,0.12), 0px 2px 4px rgba(16,24,40,0.08)",
        float: "0px 8px 24px rgba(16,24,40,0.12)",
        button: "inset 0px -2px 0px rgba(0,0,0,0.12)",
        "button-active": "inset 0px 2px 4px rgba(0,0,0,0.12)",
        toast: "0px 12px 32px rgba(16,24,40,0.18)",
      },
      spacing: {
        "section-margin": "24px",
        "touch-target-min": "50px",
        gutter: "16px",
        "container-padding": "20px",
        "element-gap": "14px",
      },
      fontFamily: {
        "headline-md": ["Inter", "Work Sans", "sans-serif"],
        "label-lg": ["Inter", "Public Sans", "sans-serif"],
        "body-md": ["Inter", "Public Sans", "sans-serif"],
        "button-text": ["Inter", "Public Sans", "sans-serif"],
        "headline-lg": ["Inter", "Work Sans", "sans-serif"],
        "metric-xl": ["Inter", "Work Sans", "sans-serif"],
        "metric-lg": ["Inter", "Work Sans", "sans-serif"],
        "display-lg": ["Inter", "Work Sans", "sans-serif"],
        "body-lg": ["Inter", "Public Sans", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-lg": ["18px", { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "button-text": ["18px", { lineHeight: "20px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "metric-xl": ["32px", { lineHeight: "32px", fontWeight: "700" }],
        "metric-lg": ["20px", { lineHeight: "24px", fontWeight: "700" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["20px", { lineHeight: "30px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
