/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#005db7",
        "primary-fixed": "#d6e3ff",
        "on-background": "#1c1b1b",
        "on-error": "#ffffff",
        "outline-variant": "#c2c6d4",
        "surface-bright": "#fcf9f8",
        "tertiary-fixed": "#ffdcbd",
        background: "#fcf9f8",
        "secondary-fixed": "#a3f69c",
        "on-secondary-fixed": "#002204",
        "surface-container-high": "#eae7e7",
        error: "#ba1a1a",
        "secondary-container": "#a0f399",
        "on-primary-fixed": "#001b3d",
        tertiary: "#734300",
        "surface-dim": "#dcd9d9",
        "secondary-fixed-dim": "#88d982",
        secondary: "#1b6d24",
        "on-surface-variant": "#424752",
        "on-primary": "#ffffff",
        "surface-variant": "#e5e2e1",
        "on-secondary-fixed-variant": "#005312",
        "on-tertiary-container": "#ffe0c4",
        "surface-container-lowest": "#ffffff",
        outline: "#727783",
        "surface-container": "#f0eded",
        "surface-container-highest": "#e5e2e1",
        "tertiary-container": "#955800",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb86e",
        "on-tertiary-fixed-variant": "#693c00",
        "inverse-primary": "#a9c7ff",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "on-surface": "#1c1b1b",
        "on-error-container": "#93000a",
        surface: "#fcf9f8",
        "on-tertiary-fixed": "#2c1600",
        "on-primary-fixed-variant": "#00468c",
        "primary-fixed-dim": "#a9c7ff",
        "primary-container": "#1565c0",
        "on-secondary-container": "#217128",
        "inverse-on-surface": "#f3f0ef",
        "inverse-surface": "#313030",
        primary: "#004d99",
        "on-primary-container": "#dae5ff",
        bone: "#F5F5F0",
      },
      spacing: {
        "section-margin": "20px",
        "touch-target-min": "50px",
        gutter: "16px",
        "container-padding": "16px",
        "element-gap": "12px",
      },
      fontFamily: {
        "headline-md": ["Work Sans", "sans-serif"],
        "label-lg": ["Public Sans", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
        "button-text": ["Public Sans", "sans-serif"],
        "headline-lg": ["Work Sans", "sans-serif"],
        "metric-xl": ["Work Sans", "sans-serif"],
        "metric-lg": ["Work Sans", "sans-serif"],
        "display-lg": ["Work Sans", "sans-serif"],
        "body-lg": ["Public Sans", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-lg": ["18px", { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "button-text": ["18px", { lineHeight: "20px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "metric-xl": ["32px", { lineHeight: "32px", fontWeight: "700" }],
        "metric-lg": ["20px", { lineHeight: "24px", fontWeight: "700" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["20px", { lineHeight: "30px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
